import React from 'react'
import ContactCard from '../components/ContactCard'
import { Email, LocationOn, Phone, WhatsApp } from '@mui/icons-material'

export const metadata = {
    title: "Contact Us | Sai General Store",
    description: "Generated by create next app",
};

function page() {
    const data = [
        {
            link: 'mailto:SAIGENERAL1310@GMAIL.COM',
            icon: <Email className='text-7xl'></Email>,
            text: 'Email'
        },
        {
            link: 'tel:+919714271310',
            icon: <Phone className='text-7xl'></Phone>,
            text: 'Phone No'
        },
        {
            link: 'https://wa.link/6qt3f2',
            icon: <WhatsApp className='text-7xl'></WhatsApp>,
            text: 'Whatsapp'
        },
        {
            link: 'https://goo.gl/maps/6M7kLMzPuDn6uZbS7',
            icon: <LocationOn className='text-7xl'></LocationOn>,
            text: 'Location'
        },
    ]
    return (
        <div className='m-16'>
            <h1 className='text-4xl text-center mb-10'>Contact Us</h1>
            <div className=''>
                <div className='flex sm:flex-row flex-col justify-center items-center w-full gap-5'>
                    {
                        data.map(item => {
                            return (
                                <ContactCard {...item} key={item.text} ></ContactCard>
                            )
                        })
                    }
                </div>
            </div>
        </div>
    )
}

export default page