import "./globals.css";
import Link from "next/link";


export const metadata = {
    title: "Home | Sai General Store",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">    
            <body className={"bg-slate-900 min-h-screen"}>
                <nav className="flex justify-between items-center w-full px-16 py-4 shadow-lg shadow-gray-900 bg-slate-950 mb-4">
                    <div className="flex">
                        <div>Logo</div>
                        <div>Name</div>
                    </div>
                    <div className="flex gap-x-8">
                        <Link href={'/'}>Home</Link>
                        <Link href={'/services'}>Services</Link>
                        <Link href={'/contact'}>Contact Us</Link>
                    </div>
                    <div>Search</div>
                </nav>
                {children}
            </body>
        </html>
    );
}
