import React from 'react'
import Card from '../components/Card'
import Link from 'next/link'

export const metadata = {
    title: "Services | Sai General Store",
    description: "Generated by create next app",
};

function page() {
    const list = [
        {
            id: 'aadhaar-card',
            title: 'Aadhaar Card',
            description: 'Services for Aadhaar Card including updates, address changes, and biometric updates.',
            image: 1
        },
        {
            id: 'pan-card',
            title: 'PAN Card',
            description: 'Services for PAN Card including new applications, corrections, and reissues.',
            image: 2
        },
        {
            id: 'driving-licence',
            title: 'Driving Licence',
            description: 'Services for Driving Licence including renewals, address changes, and new applications.',
            image: 3
        },
        {
            id: 'rc-book',
            title: 'RC Book',
            description: 'Services for RC Book including ownership transfer, address changes, and duplicate issues.',
            image: 4
        },
        {
            id: 'passport',
            title: 'Passport',
            description: 'Services for Passport including new applications, renewals, and address changes.',
            image: 5
        },
        {
            id: 'property-related-work',
            title: 'Property Related Work',
            description: 'Services related to property including registration, mutation, and document verification.',
            image: 6
        },
        {
            id: 'voter-id-card',
            title: 'Voter ID Card',
            description: 'Services for Voter ID Card including new applications, corrections, and address changes.',
            image: 7
        },
        {
            id: 'affidavit',
            title: 'Affidavit',
            description: 'Services for creating and notarizing various types of affidavits.',
            image: 8
        },
        {
            id: 'bill-payment',
            title: 'Bill Payment',
            description: 'Services for utility bill payments including electricity, water, and gas bills.',
            image: 9
        }
    ];
    
    return (
        <div className='my-12 mx-20'>
            <h1 className='w-full text-5xl text-center mb-12'>Our Services</h1>
            <div className='flex flex-wrap justify-evenly items-stretch m-4 p-4 gap-8'>
                {
                    list.map((item) => {
                        return (
                            <Link href={'/services/'+item.id} key={item.id}>
                                <Card item={item}></Card>
                            </Link>
                        )

                    })
                }
            </div>
        </div>
    )
}

export default page